imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: validator.mapping.cache.apc
#    serializer:
#        cache: serializer.mapping.cache.apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console
            
##### NO SWIFTMAILER ENTRY HERE BY DEFAULT ######

############ SAMPLE GMAIL SETUP #################
#swiftmailer:
#    transport:      smtp
#    host:           smtp-relay.gmail.com
#    port:           25
#    encryption:     tls
#    sender_address: apache@example.com
#    logging:        %kernel.debug%
    
############ SAMPLE MANDRILL SETUP ################
swiftmailer:
    transport:      smtp
    host:           smtp.mandrillapp.com
    port:           587
    encryption:     
    sender_address: vesna@vesnakovach.com
    logging:        %kernel.debug%