app_homepage:
    pattern:  /hello{name}
    defaults: { _controller: AppBundle:Default:index }
    
app_redirect:
    pattern:  /redirect
    defaults: { _controller: AppBundle:Default:redirect }

app_sendmail:
    pattern:  /sendmail
    defaults: { _controller: AppBundle:Default:sendmail }
